# Generated by Django 5.1.5 on 2026-06-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ventas", "0004_expandir_campos_ticket_tarjeta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("avatar_url", models.URLField(blank=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cliente web",
                "verbose_name_plural": "Clientes web",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="PuntoRetiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "direccion_texto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("horarios", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Punto de retiro",
                "verbose_name_plural": "Puntos de retiro",
                "ordering": ["-activo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="PedidoWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente_web",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="tienda.clienteweb",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedido_web",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido web",
                "verbose_name_plural": "Pedidos web",
                "ordering": ["-fecha"],
            },
        ),
    ]
