# Generated by Django 5.1.5 on 2026-06-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_cuenta_corriente_inicial"),
        ("tienda", "0001_add_clienteweb_pedidoweb"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloMoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=80, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=80, verbose_name="Modelo")),
                ("anio", models.IntegerField(verbose_name="Año")),
                ("activo", models.BooleanField(default=True)),
                (
                    "productos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="modelos_compatibles",
                        to="productos.productobase",
                        verbose_name="Productos compatibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de moto",
                "verbose_name_plural": "Modelos de moto",
                "ordering": ["marca", "modelo", "anio"],
                "unique_together": {("marca", "modelo", "anio")},
            },
        ),
    ]
