# Generated by Django 5.1.5 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Identificador único del parámetro', max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.CharField(help_text='Valor del parámetro (se convierte según tipo_dato)', max_length=255, verbose_name='Valor')),
                ('tipo_dato', models.CharField(choices=[('INTEGER', 'Entero'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Booleano'), ('STRING', 'Texto')], default='STRING', max_length=10, verbose_name='Tipo de Dato')),
                ('descripcion', models.TextField(help_text='Descripción del parámetro y su uso', verbose_name='Descripción')),
                ('categoria', models.CharField(help_text='Categoría del parámetro (ej: INVENTARIO, VENTAS, etc.)', max_length=50, verbose_name='Categoría')),
                ('es_editable', models.BooleanField(default=True, help_text='Indica si el parámetro puede ser modificado desde la interfaz', verbose_name='Es Editable')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['categoria', 'clave'],
                'indexes': [models.Index(fields=['clave'], name='configuraci_clave_bfe6ed_idx'), models.Index(fields=['categoria'], name='configuraci_categor_020de0_idx')],
            },
        ),
    ]
