# Generated by Django 5.1.5 on 2026-02-11 23:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número autoincremental de venta', unique=True, verbose_name='Número de Venta')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Suma de subtotales de detalles', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento %')),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuento en pesos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento $')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final a pagar', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20, verbose_name='Estado')),
                ('motivo_anulacion', models.TextField(blank=True, help_text='Requerido si la venta está anulada', null=True, verbose_name='Motivo de Anulación')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación')),
                ('cliente', models.ForeignKey(help_text='Cliente obligatorio', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente', verbose_name='Cliente')),
                ('deposito', models.ForeignKey(help_text='Depósito desde donde se realizó la venta', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.deposito', verbose_name='Depósito')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la venta', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Cajero)')),
                ('usuario_anulacion', models.ForeignKey(blank=True, help_text='Solo admin puede anular', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Anuló')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio de venta al momento de la transacción', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('descuento_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado por unidad', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='(Precio - Descuento) * Cantidad', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo del producto al momento de la venta (para margen)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='productos.varianteproducto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-fecha'], name='ventas_vent_fecha_370588_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero'], name='ventas_vent_numero_575d97_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente', '-fecha'], name='ventas_vent_cliente_bb093c_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', '-fecha'], name='ventas_vent_usuario_77be47_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_vent_estado_b0d674_idx'),
        ),
    ]
