# Generated by Django 5.1.5 on 2026-02-16 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente (opcional si la configuración CLIENTE_OBLIGATORIO está desactivada)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
