# Generated by Django 5.1.5 on 2026-06-06 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0004_expandir_campos_ticket_tarjeta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="transferencia_banco",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Banco / Billetera"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="transferencia_confirmada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferencias_confirmadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Confirmada por",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="transferencia_cuenta_destino",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Cuenta Destino / CBU / CVU",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="transferencia_estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDIENTE", "Pendiente de confirmación"),
                    ("CONFIRMADA", "Confirmada"),
                    ("RECHAZADA", "Rechazada"),
                ],
                default="",
                help_text="Solo aplica cuando metodo_pago=TRANSFERENCIA",
                max_length=12,
                verbose_name="Estado Transferencia",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="transferencia_fecha_confirmacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Confirmación"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="transferencia_numero_operacion",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="N° de Operación"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="transferencia_observacion",
            field=models.TextField(blank=True, default="", verbose_name="Observación"),
        ),
    ]
