# Generated by Django 5.1.5 on 2026-06-07 01:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("inventario", "0003_alter_movimientostock_tipo"),
        ("productos", "0004_cuenta_corriente_inicial"),
        ("ventas", "0005_transferencia_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(unique=True, verbose_name="Número")),
                (
                    "cliente_nombre_manual",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Usado cuando no hay cliente registrado",
                        max_length=200,
                        verbose_name="Nombre cliente (manual)",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Válido hasta"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, default="", verbose_name="Observaciones"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("RECHAZADO", "Rechazado"),
                            ("VENCIDO", "Vencido"),
                            ("CONVERTIDO", "Convertido a venta"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "descuento_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "deposito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="inventario.deposito",
                        verbose_name="Depósito",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presupuesto_origen",
                        to="ventas.venta",
                        verbose_name="Venta generada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ItemPresupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="productos.varianteproducto",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.presupuesto",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
