# Generated by Django 5.1.5 on 2026-02-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('CAJERO', 'Cajero'), ('ADMINISTRADOR', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('DEPOSITO', 'Depósito'), ('SUPERVISOR', 'Supervisor')], default='CAJERO', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permisos_custom',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.permiso', verbose_name='Permisos Personalizados'),
        ),
    ]
