# Generated by Django 5.1.5 on 2026-02-22 00:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0002_cuenta_corriente_inicial'),
        ('productos', '0004_cuenta_corriente_inicial'),
        ('ventas', '0002_cliente_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número autoincremental', unique=True, verbose_name='Número de ticket')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Moto 110, Reparación Juan', max_length=200, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('A_SALDAR', 'A saldar'), ('ABONADO', 'Abonado')], default='A_SALDAR', max_length=20, verbose_name='Estado')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_cuenta_corriente', to='clientes.cliente', verbose_name='Cliente')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_cuenta_corriente', to='inventario.deposito', verbose_name='Depósito')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_abiertos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que abre')),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cierra')),
                ('venta', models.ForeignKey(blank=True, help_text='Venta creada al abonar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_cuenta_corriente', to='ventas.venta', verbose_name='Venta generada')),
            ],
            options={
                'verbose_name': 'Ticket cuenta corriente',
                'verbose_name_plural': 'Tickets cuenta corriente',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTicketCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('descuento_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ticket_cc', to='productos.varianteproducto', verbose_name='Producto')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cuenta_corriente.ticketcuentacorriente', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Detalle ticket cuenta corriente',
                'verbose_name_plural': 'Detalles ticket cuenta corriente',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketcuentacorriente',
            index=models.Index(fields=['cliente', 'estado'], name='cuenta_corr_cliente_50d7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcuentacorriente',
            index=models.Index(fields=['numero'], name='cuenta_corr_numero_0032d8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcuentacorriente',
            index=models.Index(fields=['estado'], name='cuenta_corr_estado_29d4d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleticketcc',
            unique_together={('ticket', 'variante')},
        ),
    ]
