# Generated by Django 5.1.5 on 2026-06-07 02:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuenta_corriente", "0001_cuenta_corriente_inicial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcuentacorriente",
            name="fecha_vencimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de vencimiento"
            ),
        ),
        migrations.CreateModel(
            name="PagoTicketCC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("TARJETA", "Tarjeta"),
                        ],
                        default="EFECTIVO",
                        max_length=20,
                        verbose_name="Método",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(
                        blank=True, default="", verbose_name="Observación"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="cuenta_corriente.ticketcuentacorriente",
                        verbose_name="Ticket",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_cc",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago ticket CC",
                "verbose_name_plural": "Pagos ticket CC",
                "ordering": ["-fecha"],
            },
        ),
    ]
