# Generated by Django 5.1.5 on 2026-02-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('EN_PROGRESO', 'En Progreso')], default='EN_PROGRESO', max_length=20, verbose_name='Estado')),
                ('archivo', models.CharField(blank=True, max_length=255, verbose_name='Archivo')),
                ('tamanio', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('duracion', models.FloatField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que ejecutó el backup (null si es automático)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Backup',
                'verbose_name_plural': 'Logs de Backups',
                'ordering': ['-fecha'],
            },
        ),
    ]
