# Generated by Django 5.1.5 on 2026-02-12 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('AJUSTE_STOCK', 'Ajuste de Stock'), ('ANULACION', 'Anulación'), ('DEVOLUCION', 'Devolución'), ('BACKUP', 'Backup'), ('RESTAURACION', 'Restauración')], max_length=20, verbose_name='Acción')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='sistema_aud_fecha_4a4852_idx'), models.Index(fields=['usuario', '-fecha'], name='sistema_aud_usuario_8cdac6_idx'), models.Index(fields=['accion', '-fecha'], name='sistema_aud_accion_21e6a7_idx')],
            },
        ),
    ]
