# Generated by Django 5.1.5 on 2026-02-12 02:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAFIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_emisor', models.CharField(help_text='CUIT sin guiones (11 dígitos)', max_length=11, verbose_name='CUIT del Emisor')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('domicilio_comercial', models.TextField(verbose_name='Domicilio Comercial')),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], default='RI', max_length=2, verbose_name='Condición IVA')),
                ('inicio_actividades', models.DateField(verbose_name='Inicio de Actividades')),
                ('ambiente', models.CharField(choices=[('H', 'Homologación (Testing)'), ('P', 'Producción')], default='H', max_length=1, verbose_name='Ambiente AFIP')),
                ('certificado', models.TextField(blank=True, help_text='Contenido del certificado o ruta al archivo', verbose_name='Certificado (.crt)')),
                ('clave_privada', models.TextField(blank=True, help_text='Contenido de la clave privada o ruta al archivo', verbose_name='Clave Privada (.key)')),
                ('token', models.TextField(blank=True, verbose_name='Token AFIP')),
                ('sign', models.TextField(blank=True, verbose_name='Sign AFIP')),
                ('token_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del Token')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración AFIP',
                'verbose_name_plural': 'Configuración AFIP',
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de punto de venta registrado en AFIP (ej: 1, 2, 3)', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Punto de Venta')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultimo_numero_factura_a', models.IntegerField(default=0)),
                ('ultimo_numero_factura_b', models.IntegerField(default=0)),
                ('ultimo_numero_factura_c', models.IntegerField(default=0)),
                ('ultimo_numero_nota_credito_a', models.IntegerField(default=0)),
                ('ultimo_numero_nota_credito_b', models.IntegerField(default=0)),
                ('ultimo_numero_nota_credito_c', models.IntegerField(default=0)),
                ('ultimo_numero_presupuesto', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Punto de Venta',
                'verbose_name_plural': 'Puntos de Venta',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Crédito A'), ('NCB', 'Nota de Crédito B'), ('NCC', 'Nota de Crédito C'), ('PRE', 'Presupuesto')], max_length=3, verbose_name='Tipo de Comprobante')),
                ('numero', models.IntegerField(help_text='Número de comprobante', verbose_name='Número')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('cliente_razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('cliente_cuit', models.CharField(max_length=13, verbose_name='CUIT/CUIL/DNI')),
                ('cliente_condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], max_length=2, verbose_name='Condición IVA')),
                ('cliente_domicilio', models.TextField(blank=True, verbose_name='Domicilio')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal (sin IVA)')),
                ('iva_105', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA 10.5%')),
                ('iva_21', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA 21%')),
                ('iva_27', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA 27%')),
                ('otros_tributos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Otros Tributos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('cae', models.CharField(blank=True, help_text='Código de Autorización Electrónico', max_length=14, verbose_name='CAE')),
                ('cae_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento CAE')),
                ('fecha_proceso_afip', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Proceso AFIP')),
                ('resultado_afip', models.CharField(blank=True, help_text='A=Aprobado, R=Rechazado', max_length=1)),
                ('observaciones_afip', models.TextField(blank=True, verbose_name='Observaciones AFIP')),
                ('qr_data', models.TextField(blank=True, help_text='Datos para generar código QR', verbose_name='Datos QR')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='ventas.venta', verbose_name='Venta Asociada')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.puntoventa', verbose_name='Punto de Venta')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario')),
                ('alicuota_iva', models.CharField(choices=[('0', '0% (Exento)'), ('10.5', '10.5%'), ('21', '21%'), ('27', '27%')], default='21', max_length=5, verbose_name='Alícuota IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('iva_105', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA 10.5%')),
                ('iva_21', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA 21%')),
                ('iva_27', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA 27%')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Ítem de Factura',
                'verbose_name_plural': 'Ítems de Factura',
                'ordering': ['factura', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_emision'], name='facturacion_fecha_e_154b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente', 'fecha_emision'], name='facturacion_cliente_a4764b_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='facturacion_estado_b4dd64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('punto_venta', 'tipo_comprobante', 'numero')},
        ),
    ]
