# Generated by Django 5.1.5 on 2026-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="pdf_archivo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ruta relativa en MEDIA_ROOT, ej: facturas/factura_venta_000123_B_0001_00000001.pdf",
                max_length=500,
                verbose_name="Archivo PDF",
            ),
        ),
    ]
