# Generated by Django 5.1.5 on 2026-06-07 02:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="descuento_habitual",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Descuento sugerido en el POS para este cliente",
                max_digits=5,
                verbose_name="Descuento habitual %",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="limite_credito",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monto máximo en cuenta corriente. 0 = sin límite",
                max_digits=12,
                verbose_name="Límite de crédito",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="notas",
            field=models.TextField(
                blank=True, default="", verbose_name="Notas internas"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.CharField(
                choices=[
                    ("MINORISTA", "Minorista"),
                    ("MAYORISTA", "Mayorista"),
                    ("MECANICO", "Mecánico / Taller"),
                    ("REVENDEDOR", "Revendedor"),
                ],
                default="MINORISTA",
                max_length=12,
                verbose_name="Tipo de cliente",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número sin espacios ni guiones. Ej: 3834625390",
                max_length=50,
                verbose_name="WhatsApp",
            ),
        ),
    ]
