# Generated by Django 5.1.5 on 2026-02-11 22:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto Base',
                'verbose_name_plural': 'Productos Base',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(help_text='Ej: STD, 0.25, 0.50, Rojo, Talle M', max_length=100, verbose_name='Nombre de Variante')),
                ('codigo', models.CharField(db_index=True, help_text='Código único del producto (puede ser código de barras, SKU, etc.)', max_length=100, unique=True, verbose_name='Código')),
                ('costo', models.DecimalField(decimal_places=2, help_text='Último costo de compra', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo (último costo)')),
                ('precio_mostrador', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Mostrador')),
                ('precio_web', models.DecimalField(decimal_places=2, help_text='Precio para tienda online', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Web')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('producto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.productobase', verbose_name='Producto Base')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['producto_base__nombre', 'nombre_variante'],
            },
        ),
        migrations.AddIndex(
            model_name='productobase',
            index=models.Index(fields=['nombre'], name='productos_p_nombre_c6342b_idx'),
        ),
        migrations.AddIndex(
            model_name='productobase',
            index=models.Index(fields=['marca', 'categoria'], name='productos_p_marca_i_89daf8_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['codigo'], name='productos_v_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['producto_base', 'activo'], name='productos_v_product_3f360d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='varianteproducto',
            unique_together={('producto_base', 'nombre_variante')},
        ),
    ]
