# Generated by Django 5.1.5 on 2026-02-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_precio_tarjeta_costo_mas_84'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='varianteproducto',
            new_name='productos_v_codigo_414e8f_idx',
            old_name='productos_v_codigo_idx',
        ),
    ]
