# Generated by Django 5.1.5 on 2026-06-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_cuenta_corriente_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="varianteproducto",
            name="punto_reorden",
            field=models.IntegerField(
                blank=True,
                help_text="Cantidad a reponer cuando se alcanza el stock mínimo",
                null=True,
                verbose_name="Punto de Reorden",
            ),
        ),
        migrations.AddField(
            model_name="varianteproducto",
            name="stock_minimo",
            field=models.IntegerField(
                default=0,
                help_text="Cantidad mínima deseada. 0 = usar umbral global",
                verbose_name="Stock Mínimo",
            ),
        ),
    ]
