# Generated by Django 5.1.5 on 2026-06-08 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_fase8_compras_ordenes"),
        ("productos", "0005_fase7_inventario_avanzado"),
    ]

    operations = [
        migrations.AddField(
            model_name="varianteproducto",
            name="proveedor_habitual",
            field=models.ForeignKey(
                blank=True,
                help_text="Proveedor por defecto para este producto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos_habituales",
                to="compras.proveedor",
                verbose_name="Proveedor Habitual",
            ),
        ),
    ]
