# Generated by Django 5.1.5 on 2026-06-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0006_fase8_compras_ordenes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="productos/imagenes/", verbose_name="Imagen"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "es_principal",
                    models.BooleanField(default=False, verbose_name="Es principal"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "producto_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="productos.productobase",
                        verbose_name="Producto base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de producto",
                "verbose_name_plural": "Imágenes de productos",
                "ordering": ["orden", "id"],
            },
        ),
    ]
