# Generated by Django 5.1.5 on 2026-02-12 00:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número autoincremental de devolución', unique=True, verbose_name='Número de Devolución')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Devolución')),
                ('motivo', models.CharField(choices=[('DEFECTO', 'Defecto en el producto'), ('INCORRECTO', 'Producto incorrecto'), ('ARREPENTIMIENTO', 'Arrepentimiento del cliente'), ('ERROR', 'Error en la venta'), ('GARANTIA', 'Garantía'), ('OTRO', 'Otro motivo')], help_text='Motivo de la devolución', max_length=20, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, help_text='Detalles adicionales sobre la devolución', null=True, verbose_name='Observaciones')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la devolución', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADA', 'Procesada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('genera_nota_credito', models.BooleanField(default=True, help_text='Si debe generar una nota de crédito para el cliente', verbose_name='Genera Nota de Crédito')),
                ('deposito', models.ForeignKey(help_text='Depósito donde reingresan los productos', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventario.deposito', verbose_name='Depósito')),
                ('usuario', models.ForeignKey(help_text='Usuario que procesó la devolución', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta', verbose_name='Venta Original')),
            ],
            options={
                'verbose_name': 'Devolución de Venta',
                'verbose_name_plural': 'Devoluciones de Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de unidades devueltas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al que se vendió originalmente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Cantidad * Precio Unitario', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subtotal')),
                ('estado_producto', models.CharField(blank=True, help_text='Condición en la que se devuelve (ej: nuevo, usado, dañado)', max_length=50, null=True, verbose_name='Estado del Producto')),
                ('detalle_venta', models.ForeignKey(help_text='Detalle original de la venta', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.detalleventa', verbose_name='Detalle de Venta')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='productos.varianteproducto', verbose_name='Producto')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='devoluciones.devolucionventa', verbose_name='Devolución')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de Nota de Crédito')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('monto_utilizado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto Utilizado')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Opcional. Si no se especifica, no vence.', null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('UTILIZADA', 'Utilizada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='clientes.cliente', verbose_name='Cliente')),
                ('devolucion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito', to='devoluciones.devolucionventa', verbose_name='Devolución')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['-fecha'], name='devolucione_fecha_a5647d_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['numero'], name='devolucione_numero_90e3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['venta'], name='devolucione_venta_i_1a6e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['estado'], name='devolucione_estado_4925ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalledevolucion',
            unique_together={('devolucion', 'detalle_venta')},
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['numero'], name='devolucione_numero_ae5fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['cliente'], name='devolucione_cliente_dc5e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['estado'], name='devolucione_estado_95d803_idx'),
        ),
    ]
