# Generated by Django 5.1.5 on 2026-02-11 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_principal', models.BooleanField(default=False, help_text='Depósito por defecto para operaciones', verbose_name='Depósito Principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('DEVOLUCION', 'Devolución'), ('ANULACION', 'Anulación'), ('AJUSTE', 'Ajuste Manual'), ('TRANSFERENCIA', 'Transferencia'), ('INVENTARIO_INICIAL', 'Inventario Inicial')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(help_text='Positivo para entradas, negativo para salidas', verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('referencia_tipo', models.CharField(blank=True, help_text='Ej: venta, compra, ajuste', max_length=50, null=True, verbose_name='Tipo de Referencia')),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID del documento relacionado', null=True, verbose_name='ID de Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock Anterior')),
                ('stock_posterior', models.IntegerField(verbose_name='Stock Posterior')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.deposito', verbose_name='Depósito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.varianteproducto', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['variante', 'deposito', '-fecha'], name='inventario__variant_2e15d6_idx'), models.Index(fields=['tipo', '-fecha'], name='inventario__tipo_624c45_idx'), models.Index(fields=['usuario', '-fecha'], name='inventario__usuario_e8521c_idx'), models.Index(fields=['referencia_tipo', 'referencia_id'], name='inventario__referen_a9e50c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad actual en stock (puede ser negativa)', verbose_name='Cantidad')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventario.deposito', verbose_name='Depósito')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productos.varianteproducto', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['variante__producto_base__nombre', 'variante__nombre_variante'],
                'indexes': [models.Index(fields=['variante', 'deposito'], name='inventario__variant_788405_idx'), models.Index(fields=['cantidad'], name='inventario__cantida_6a3b29_idx')],
                'unique_together': {('variante', 'deposito')},
            },
        ),
    ]
