# Generated by Django 5.1.5 on 2026-02-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('DEVOLUCION', 'Devolución'), ('ANULACION', 'Anulación'), ('AJUSTE', 'Ajuste Manual'), ('TRANSFERENCIA', 'Transferencia'), ('INVENTARIO_INICIAL', 'Inventario Inicial'), ('SALIDA_TICKET_CC', 'Salida ticket cuenta corriente'), ('DEVOLUCION_TICKET_CC', 'Devolución ticket cuenta corriente')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
    ]
