# Generated by Django 5.1.5 on 2026-06-07 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_movimientostock_tipo"),
        ("productos", "0005_fase7_inventario_avanzado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConteoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ABIERTO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cierre"
                    ),
                ),
                (
                    "deposito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conteos",
                        to="inventario.deposito",
                        verbose_name="Depósito",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conteos_inventario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteo de Inventario",
                "verbose_name_plural": "Conteos de Inventario",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="DetalleConteo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_sistema",
                    models.IntegerField(verbose_name="Cantidad en sistema"),
                ),
                (
                    "cantidad_contada",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Cantidad contada"
                    ),
                ),
                (
                    "ajustado",
                    models.BooleanField(default=False, verbose_name="Ajustado"),
                ),
                (
                    "conteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.conteoinventario",
                        verbose_name="Conteo",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_conteo",
                        to="productos.varianteproducto",
                        verbose_name="Variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Conteo",
                "verbose_name_plural": "Detalles de Conteo",
                "ordering": [
                    "variante__producto_base__nombre",
                    "variante__nombre_variante",
                ],
                "unique_together": {("conteo", "variante")},
            },
        ),
    ]
