# Generated by Django 5.1.5 on 2026-02-17 21:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0002_cliente_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: POS Principal, Caja 2', max_length=100, verbose_name='Nombre')),
                ('merchant_id', models.CharField(help_text='ID del comercio en Clover', max_length=100, verbose_name='Merchant ID')),
                ('access_token', models.TextField(help_text='Token OAuth de Clover (en producción usar encriptación)', verbose_name='Access Token')),
                ('tipo_integracion', models.CharField(choices=[('REST', 'REST Pay Display (red local)'), ('CLOUD', 'Cloud Pay Display (nube)')], default='REST', max_length=10, verbose_name='Tipo de integración')),
                ('endpoint_url', models.CharField(help_text='REST: http://IP_DISPOSITIVO:8080 | Cloud: https://api.clover.com', max_length=500, verbose_name='URL del endpoint')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Clover',
                'verbose_name_plural': 'Configuraciones Clover',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CloverPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clover_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID pago Clover')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('estado', models.CharField(choices=[('APPROVED', 'Aprobado'), ('DECLINED', 'Rechazado'), ('CANCELLED', 'Cancelado'), ('ERROR', 'Error')], max_length=20, verbose_name='Estado')),
                ('metodo_tarjeta', models.CharField(blank=True, help_text='CREDIT, DEBIT, etc.', max_length=50, verbose_name='Tipo tarjeta')),
                ('ultimos_4_digitos', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos')),
                ('datos_respuesta', models.JSONField(blank=True, default=dict, verbose_name='Respuesta Clover')),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_clover', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago Clover',
                'verbose_name_plural': 'Pagos Clover',
                'ordering': ['-fecha_procesamiento'],
                'indexes': [models.Index(fields=['clover_payment_id'], name='clover_clov_clover__f1b362_idx'), models.Index(fields=['estado'], name='clover_clov_estado_284a58_idx'), models.Index(fields=['-fecha_procesamiento'], name='clover_clov_fecha_p_8ac1b6_idx')],
            },
        ),
    ]
