# Generated by Django 5.1.5 on 2026-02-11 23:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Proveedor')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número autoincremental de compra', unique=True, verbose_name='Número de Compra')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_compra', models.DateField(blank=True, help_text='Fecha real de la compra (opcional)', null=True, verbose_name='Fecha de Compra')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la compra', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('numero_factura', models.CharField(blank=True, help_text='Número de factura del proveedor', max_length=50, null=True, verbose_name='Número de Factura')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('PENDIENTE', 'Pendiente'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', max_length=20, verbose_name='Estado')),
                ('deposito', models.ForeignKey(help_text='Depósito donde ingresa la mercadería', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.deposito', verbose_name='Depósito')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró la compra', on_delete=django.db.models.deletion.PROTECT, related_name='compras_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo de compra por unidad', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Costo Unitario * Cantidad', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('precio_venta_sugerido', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta sugerido para esta compra', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta Sugerido')),
                ('actualizar_costo', models.BooleanField(default=True, help_text='Si se debe actualizar el costo del producto con este valor', verbose_name='Actualizar Costo del Producto')),
                ('actualizar_precio', models.BooleanField(default=False, help_text='Si se debe actualizar el precio de venta del producto', verbose_name='Actualizar Precio de Venta')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra', verbose_name='Compra')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='productos.varianteproducto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['-fecha'], name='compras_com_fecha_f13a73_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['numero'], name='compras_com_numero_9e742f_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['proveedor', '-fecha'], name='compras_com_proveed_9a1c87_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['usuario', '-fecha'], name='compras_com_usuario_4c72a2_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['estado'], name='compras_com_estado_d26ae1_idx'),
        ),
    ]
