# Generated by Django 5.1.5 on 2026-02-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraFacturaAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.ImageField(
                        help_text="Imagen de la factura (JPEG/PNG, se comprime al subir)",
                        upload_to="compras_facturas/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de subida"
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos_factura",
                        to="compras.compra",
                        verbose_name="Compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto de factura",
                "verbose_name_plural": "Adjuntos de facturas",
                "ordering": ["compra", "orden", "id"],
            },
        ),
    ]
