# Generated by Django 5.1.5 on 2026-06-08 01:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_adjuntos_factura"),
        ("inventario", "0004_fase7_inventario_avanzado"),
        ("productos", "0005_fase7_inventario_avanzado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.IntegerField(unique=True, verbose_name="Número de Orden"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EMITIDA", "Emitida"),
                            ("RECIBIDA_PARCIAL", "Recibida Parcialmente"),
                            ("RECIBIDA_TOTAL", "Recibida Totalmente"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "fecha_esperada",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha esperada de recepción",
                    ),
                ),
                (
                    "numero_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Número de cotización/referencia del proveedor",
                        max_length=100,
                        null=True,
                        verbose_name="N° referencia proveedor",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones internas"
                    ),
                ),
                (
                    "notas_proveedor",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas para el proveedor"
                    ),
                ),
                (
                    "deposito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_compra",
                        to="inventario.deposito",
                        verbose_name="Depósito de destino",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_compra",
                        to="compras.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_compra",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_pedida",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad pedida",
                    ),
                ),
                (
                    "cantidad_recibida",
                    models.IntegerField(default=0, verbose_name="Cantidad recibida"),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo estimado unitario",
                    ),
                ),
                (
                    "costo_real",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo real unitario (al recibir)",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_compra",
                        to="productos.varianteproducto",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.ordencompra",
                        verbose_name="Orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Orden de Compra",
                "verbose_name_plural": "Detalles de Órdenes de Compra",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HistorialCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "costo_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo Anterior"
                    ),
                ),
                (
                    "costo_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo Nuevo"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "referencia_tipo",
                    models.CharField(
                        blank=True,
                        help_text="compra, orden, manual",
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de referencia",
                    ),
                ),
                (
                    "referencia_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de referencia"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cambios_costo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_costos",
                        to="productos.varianteproducto",
                        verbose_name="Variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Costo",
                "verbose_name_plural": "Historial de Costos",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["variante", "-fecha"],
                        name="compras_his_variant_4a96c9_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ordencompra",
            index=models.Index(fields=["numero"], name="compras_ord_numero_c3c69c_idx"),
        ),
        migrations.AddIndex(
            model_name="ordencompra",
            index=models.Index(
                fields=["proveedor", "-fecha_emision"],
                name="compras_ord_proveed_676859_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordencompra",
            index=models.Index(fields=["estado"], name="compras_ord_estado_4a72b0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="detalleordencompra",
            unique_together={("orden", "variante")},
        ),
    ]
